version: "3.8"
name: "foodgram-prod"

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - foodgram-network
    env_file:
      - ./.env.db

  backend:
    build: ../../backend/
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - foodgram-network
    depends_on:
      - db
    env_file:
      - ./.env.backend
      - ./.env.db

  frontend:
    build: ../../frontend/
    container_name: frontend
    env_file:
      - ./.env.frontend
    volumes:
      - frontend_build:/app/build/

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - frontend_build:/usr/share/nginx/html/
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - foodgram-network
    restart: always
    env_file:
      - ./.env.nginx
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  db_data:
  frontend_build:

networks:
  foodgram-network:
