version: "3.8"
name: "foodgram-dev"

services:
  db:
    image: postgres:13.0-alpine
    container_name: dev-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

volumes:
  db_data:
