version: '3.8'
name: "foodgram"

services:
  db:
    image: postgres:13.0-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  backend:
    build: ../backend/
    container_name: backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env.backend
      - ./.env.db
    links:
      - db

  frontend:
    build: ../frontend/
    container_name: frontend
    env_file:
      - ./.env.frontend
    volumes:
      - ../frontend_build/:/app/build/

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - static_value:/var/html/static
      - media_value:/var/html/media
      - ../frontend_build:/usr/share/nginx/html/
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    restart: always
    env_file:
      - ./.env.backend
    depends_on:
      - backend
      - frontend
    links:
      - backend

volumes:
  static_value:
  media_value:
  db_data:
