version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  frontend:
    build: ../frontend/
    ports:
      - "8001:80"


volumes:
  db_data:
