# Generated by Django 2.2.28 on 2023-08-31 08:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_change_color_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Тэги', related_name='recipes', to='recipes.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, help_text='HEX-код цвета', max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag(2), message='Цвет в формате HEX', regex='^[A-F\\d]{6}$')], verbose_name='HEX-код'),
        ),
    ]
